### ISSUE TITLE
ClickHouse exactly once?

### ISSUE THREAD

**Issue by filimonov** [adform/stream-loader#10]
1) on the system with several replicas `committedPositions` can return different values on different replicas (due to eventual consistency). So it may work only on a single replica or with insert_quorum/sequential_consistency?

 https://github.com/adform/stream-loader/blob/97ebefc54638ce6da527555339846de57ab119fa/stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileStorage.scala#L38 

2) similarly it looks like that code relies on the strict linear order of inserts (no parallel inserts?). Does it mean single replica only + insert_quorum + insert_quorum_parallel=0 ? 

3) idempotent retries? In case of insert failure (or worse: quorum failure) - is there any guarantee that during the next retry you will repeat exactly the same block?

**Comment by sauliusvl** [comment]
Hi, sorry for the late reply. You're correct that currently essentially only a single replica is supported and the we have not really tested what happens with more replicas and parallel inserts (we should add a warning somewhere). 

Regarding your third point, on insert failure before retrying we [check](https://github.com/adform/stream-loader/blob/master/stream-loader-core/src/main/scala/com/adform/streamloader/batch/RecordBatchingSinker.scala#L76) whether the insert actually succeeded (query for the offsets) and only then retry submitting the same exact file, if needed. If storing fails and the application restarts before retrying, after startup it will construct a new file, which can be different from the previously attempted one either because the user-defined mapping is non-deterministic, or the file completion policy is non-deterministic (e.g. if using the [FuzzyReachedAnyOf](https://github.com/adform/stream-loader/blob/master/stream-loader-core/src/main/scala/com/adform/streamloader/file/FileCommitStrategy.scala#L60) completion strategy).

Suggestions for improving the ClickHouse sink are very welcome. It was not easy figuring out the provided guarantees when writing the original code, all I could find was that it's important to set `MAX_INSERT_BLOCK_SIZE` to the number of rows in the file (as is done [here](https://github.com/adform/stream-loader/blob/master/stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileStorage.scala#L86)), but not much regarding replicated and distributed tables. I assume a lot has happened with ClickHouse since then :)
